### ISSUE TITLE
iOS - Keyboard causes issues with typing

### ISSUE THREAD

**Issue by rmevans9** [wix/Detox#1254]
**Describe the bug**
When using a iPad simulator that has recently been wiped the keyboard could show the "tutorial" for using the pull down to use alternative keys (like the numbers, special characters, etc). This is exactly the same issue as here: https://github.com/wix/Detox/issues/677

**To Reproduce**

- [X] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Write a test that goes into a text field and enter a special character or number
2. Observe that the tutorial shows and you are unable to move forward.

**Expected behavior**
Either keep the tutorial from showing or handle clicking ok before moving on to the next step

**Screenshots**
<img width="679" alt="Screen Shot 2019-04-04 at 11 22 48 AM" src="https://user-images.githubusercontent.com/14151327/55567598-ff1dbe80-56cb-11e9-8cd3-f52787f25c8e.png">

**Environment (please complete the following information):**
 - Detox: 12.1.2
 - React Native: 0.59.3
 - Node: 11.10.1
 - Device: iPad Pro (10.5")
 - Xcode: 10.2
 - iOS: 12.2
 - macOS: 10.14.4

**Comment by LeoNatan** [comment]
I think this is a limitation with Earl Grey, the underlying project we use to generate touches and actions.
It is worth investigating, however. There is most probably a user defaults value that Apple sets to no longer display this tutorial. I will take a look.

**Comment by LeoNatan** [comment]
It seems this was already fixed by the Google team: https://github.com/google/EarlGrey/issues/633
And we should be using the latest EG with this fix.
@rmevans9 Could you please test on an iOS 11 simulator, just to see if the issue does not reproduce there?
Could be that Apple changed something in iOS 12.x and broke their fix.

**Comment by rmevans9** [comment]
I sure can. I will be grabbing 11.4 to try this out on. Will report back here in a little bit.

**Comment by LeoNatan** [comment]
Great, thanks! I just checked, and indeed, the version of EG we use has the fix in the issue I linked. So if it's only in iOS 12.x, I will investigate and provide a PR to EG.

**Comment by rmevans9** [comment]
I just tried it on 11.4 and the tutorial screen still showed up and caused my test to not be able to continue. One thing I noted with this test though is if I do a test that triggers the tutorial and then does nothing else all following tests are able to get through since the device no longer shows the tutorial screen.

**Comment by LeoNatan** [comment]
Dang. I will test next week to see why the workaround code in EG is not working.
Regarding the followup tests, it makes sense. The system has noted that the tutorial has been shown up, and so will not display it again.

**Comment by thomaschriskelly** [comment]
In case it helps anyone else, my workaround for this issue is to place this before other tests:

```
await element(by.id(RANDOM_FIELD)).typeText('+').catch(() => null);
await element(by.text('OK')).tap().catch(() => null);
await element(by.id(RANDOM_FIELD)).replaceText('');
```

**Comment by LeoNatan** [comment]
Is this not solved by latest Earl Grey?

**Comment by LeoNatan** [comment]
Please install Detox 13.0.0 and try.
