### ISSUE TITLE
Touchable inside FullWindowOverlay can't be pressed by Detox

### ISSUE THREAD

**Issue by adamivancza** [wix/Detox#3728]
### What happened?

We have a custom Toast component that is using FullWindowOverlay (by react-native-screens) so we can display a Toast even above Modals. However when we're trying to tap on a touchable inside this detox fails to do so. We get the following error message:
```
Test Failed: View is not hittable at its visible point. Error: Failed to hit view with identifier `toast-pressable` at point {207, 805.5} with hit-test
    - Origin view: <RCTRootView: 0x7fb332b06ee0; frame = (0 0; 414 896); autoresize = W+H; backgroundColor = <UIDynamicSystemColor: 0x600003c57ec0; name = systemBackgroundColor>; layer = <CALayer: 0x600002945a00>>
    - Absolute origin: {0, 0}
    - Hit: <RCTView: 0x7fb322818320; reactTag: 17; frame = (0 48; 414 814); backgroundColor = UIExtendedSRGBColorSpace 1 1 1 1; layer = <CALayer: 0x6000029412c0>>
    - Target view: <RCTView: 0x7fb332a08490; reactTag: 45; frame = (16 0; 382 17); layer = <CALayer: 0x600002f80300>>
    - Relative point: {207, 805.5}
 ```
If I replace FullWindowOverlay with a plain View tests works fine.

### What was the expected behaviour?

Touchables inside FullWindowOverlay should also be tappable by Detox

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

https://drive.google.com/file/d/1owxETvumtwaSicHpp8moAtda3AEdNQ2t/view?usp=sharing

### In what environment did this happen?

Detox version: 20.0.3
React Native version: 0.70.6 
Node version: v14 latest
Device model: iPhone 11
iOS version: 16.0
macOS version: 12.6
Xcode version: 14.0
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by asafkorem** [comment]
Hey @adamivancza, thanks for the report.

Can you please provide here the UI-hierarchy artifact of the failing test (along with its error [from the same test run], that contains the view IDs)? Also, I recommend that you'll try to check it yourself.

The artifact can be generated using `--capture-view-hierarchy enabled` launch argument or `"uiHierarchy": "enabled",` under the plugins config.
See our Artifacts doc: https://wix.github.io/Detox/docs/next/config/artifacts

**Comment by asafkorem** [comment]
Also, thanks for the reproduction code. I'll take a look soon!

**Comment by adamivancza** [comment]
hey @asafkorem! here you go:
[ui.viewhierarchy.zip](https://github.com/wix/Detox/files/10083219/ui.viewhierarchy.zip)

**Comment by asafkorem** [comment]
Hey @adamivancza, thanks for the artifact and the log.

Looks like the toast is indeed a top view, I also used your reproduction project, thanks for that.
<img width="954" alt="image" src="https://user-images.githubusercontent.com/55082339/203771316-60f80c38-578e-416c-8a0d-3938680d05fd.png">

I suspect that this `FullWindowOverlay` object is a regular view that is a direct subview of the UIWindow, and not a child of any view-controller, so this might be the reason why Detox can't identify it as a top view (note that the "Origin View" is not a parent of this view, that's because we have an assumption that all views must be under a view controller).

I'll try to figure what will be the best way to identify such cases.

**Comment by adamivancza** [comment]
@asafkorem if that helps anything this works perfectly in Detox v19

**Comment by Fortidude** [comment]
Same problem here. In v19 it works perfectly, in v20:

```
    Test Failed: View is not hittable at its visible point. Error: Failed to hit view with identifier `TestUtils_Logout_Button` at point {85.75, 56} with hit-test
    - Origin view: <RCTRootView: 0x158e291b0; frame = (0 0; 414 896); autoresize = W+H; layer = <CALayer: 0x600002af4440>>
    - Absolute origin: {0, 0}
    - Hit: <RCTView: 0x14dfe8ff0; reactTag: 155; frame = (0 0; 414 896); layer = <CALayer: 0x600002c06b60>> (identifier: `ThemedView`)
    - Target view: <RCTView: 0x2ea405fe0; reactTag: 253; frame = (63 0; 33.5 16); layer = <CALayer: 0x600002c29580>>
    - Relative point: {85.75, 56}

```

**Comment by asafkorem** [comment]
> Same problem here. In v19 it works perfectly, in v20 (20.0.3) the below errors:
> 
> ```
>     Test Failed: View is not hittable at its visible point. Error: Failed to hit view with identifier `TestUtils_Logout_Button` at point {85.75, 56} with hit-test
>     - Origin view: <RCTRootView: 0x158e291b0; frame = (0 0; 414 896); autoresize = W+H; layer = <CALayer: 0x600002af4440>>
>     - Absolute origin: {0, 0}
>     - Hit: <RCTView: 0x14dfe8ff0; reactTag: 155; frame = (0 0; 414 896); layer = <CALayer: 0x600002c06b60>> (identifier: `ThemedView`)
>     - Target view: <RCTView: 0x2ea405fe0; reactTag: 253; frame = (63 0; 33.5 16); layer = <CALayer: 0x600002c29580>>
>     - Relative point: {85.75, 56}
> ```

Is that really the same problem? Do you use a FullWindowOverlay?

**Comment by asafkorem** [comment]
Hi @adamivancza, I merged a fix for your issue, we plan to push it with the next Detox release. I'll update here once we'll release a new version (probably later today).

**Comment by adamivancza** [comment]
awesome, thank you @asafkorem

**Comment by asafkorem** [comment]
Hey @adamivancza, have you tested the new release (20.1.0) yet?

**Comment by adamivancza** [comment]
@asafkorem sorry for the late reply here but my repro project still fails with the same issue even with 20.1.1

**Comment by adamivancza** [comment]
Please do not close this

**Comment by asafkorem** [comment]
> @asafkorem sorry for the late reply here but my repro project still fails with the same issue even with 20.1.1

Hi @adamivancza, do you have the same error or something similar? If it's not exactly the same please post here the logs.

It will be much easier to investigate if I'll have a reproducer, is it possible that you'll extract & provide me with the code of the minimal component and test that reproduces this error using https://github.com/wix-incubator/detoxtemplate ?

**Comment by adamivancza** [comment]
yeah same exact issue @asafkorem

**Comment by adamivancza** [comment]
@asafkorem here is a repro project using your template project
[detoxtemplate.zip](https://github.com/wix/Detox/files/10815734/detoxtemplate.zip)

**Comment by d4vidi** [comment]
> @asafkorem here is a repro project using your template project [detoxtemplate.zip](https://github.com/wix/Detox/files/10815734/detoxtemplate.zip)

Thank you!!! We will look into it asap

**Comment by asafkorem** [comment]
Thanks @adamivancza, I will check that.

**Comment by asafkorem** [comment]
@adamivancza in your reproduction project, it seems that you're using `FullWindowOverlay`, which doesn't have a `style` property but you're still passing it a `style` attribute.

See react-native-screens' documentation:
https://github.com/software-mansion/react-native-screens#fullwindowoverlay
> You should treat it as a wrapper, providing full-screen, transparent view which receives no props and should ideally render one child View, being the root of its view hierarchy.

Based on their documentation, I made my own reproduction of this component test (with FullWindowOverlay) on our test project and it passes the test. See this commit for a reference: https://github.com/wix/Detox/commit/f652500a30eddde5f0dc48f91a1482997874cb85

**Comment by d4vidi** [comment]
So can this be closed?

**Comment by asafkorem** [comment]
@d4vidi I believe so. @adamivancza please check my suggestion and update us correspondingly.

**Comment by adamivancza** [comment]
@asafkorem @d4vidi it's still failing for me :/ 
I'm using the same RN and react-native-screens version as you are, and I've updated my component as well to not pass in the style attribute to the `FullWindowOverlay`.
Any chance that you can run my repro project locally and lmk whether you can repro the issue that way?

```
Test Failed: View is not hittable at its visible point. Error: Failed to hit view with identifier `toast-pressable` at point {207, 813.5} with hit-test
    - Origin view: <UITransitionView: 0x7fe1c4831260; frame = (0 0; 414 896); autoresize = W+H; layer = <CALayer: 0x60000023f4c0>>
    - Absolute origin: {0, 0}
    - Hit: <RCTView: 0x7fe1c4e10dd0; reactTag: 43; frame = (0 48; 414 814); backgroundColor = UIExtendedSRGBColorSpace 1 1 1 1; layer = <CALayer: 0x60000026c860>>
    - Target view: <RCTView: 0x7fe1c4bb08f0; reactTag: 69; frame = (150 20; 114 57); layer = <CALayer: 0x6000004e5f80>>
    - Relative point: {207, 813.5}
```

**Comment by adamivancza** [comment]
[DetoxTouchRepro 2.zip](https://github.com/wix/Detox/files/10870440/DetoxTouchRepro.2.zip)

**Comment by asafkorem** [comment]
@adamivancza please check the commit I provided you. I see no issue with Touchable inside FullWindowOverlay, so there might be a different issue here. Please use my commit as a reference for working with FullWindowOverlay
https://github.com/wix/Detox/issues/3728#issuecomment-1445395118

**Comment by iacovlev-pavel** [comment]
While upgrading Detox from 19 to 20, in a project that uses UI Kitten, all the components that use a Modal seems to error out with the following message:
```
Test Failed: View is not hittable at its visible point. Error: View is not visible around point.
    - view point: {195, 421.99996948242188}
    - visible bounds: {{0, 0}, {390, 843.99993896484375}}
    - view bounds: {{0, 0}, {390, 843.99993896484375}}
    ---
    Error: Error Domain=DetoxErrorDomain Code=0 "View “<RCTView: 0x15925a9e0>” is not visible: View does not pass visibility percent threshold (100)" UserInfo={NSLocalizedDescription=View “<RCTView: 0x15925a9e0>” is not visible: View does not pass visibility percent threshold (100)}
```
https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/modal/modal.component.tsx

I am able to open the Modal but not able to close it.
