### ISSUE TITLE
App started to crash when running tests after react-native-firebase/perf module been added

### ISSUE THREAD

**Issue by jeferson-sb** [wix/Detox#4109]
### What happened?

After I've added the @react-native-firebase/perf package to the app every test seems to be failure due to a premature crash. The same app has other firebase dependencies and it was working just fine.
 
![image](https://github.com/wix/Detox/assets/30840709/608890b5-0cb2-4ab8-a028-c8c34369714f)

Please see the logs on as well.

### What was the expected behaviour?

Tests should run without any crashes.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.9.1
React Native version: 0.68.6
Has Fabric (React Native's new rendering system) enabled: (yes/no) no
Node version: 18.16.0
Device model: Emulator Pixel XL API 33
Android version: 13
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
18:35:23.055 detox[91222] B artifacts-manager onLaunchApp
  args: ({"deviceId":"emulator-17034","bundleId":"com.apptest","launchArgs":{"detoxServer":"ws://localhost:42627","detoxSessionId":"56e33148-6998-daa5-6a0e-e22f56dcc764"},"pid":5385})
18:35:23.055 detox[91222] E artifacts-manager onLaunchApp
18:35:23.356 detox[91222] i child-process:SPAWN_STDOUT INSTRUMENTATION_STATUS: stack=java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/~~ZjzWRipsXQSU-EhBqXU3XA==/com.apptest.test-oxzNM_LcBE-m2KgsfnRqFg==/base.apk)
	at com.google.firebase.perf.v1.TraceMetric.<clinit>(TraceMetric.java:1945)
	at com.google.firebase.perf.v1.TraceMetric.newBuilder(TraceMetric.java:941)
	at com.google.firebase.perf.metrics.AppStartTrace.<init>(AppStartTrace.java:194)
	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:171)
	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:158)
	at com.google.firebase.perf.FirebasePerfEarly.<init>(FirebasePerfEarly.java:49)
	at com.google.firebase.perf.FirebasePerfRegistrar.lambda$getComponents$0(FirebasePerfRegistrar.java:75)
	at com.google.firebase.perf.FirebasePerfRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(Lazy.java:53)
	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:606)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:299)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:263)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:248)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

INSTRUMENTATION_STATUS: stream=
Process crashed before executing the test(s):
java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/~~ZjzWRipsXQSU-EhBqXU3XA==/com.apptest.test-oxzNM_LcBE-m2KgsfnRqFg==/base.apk)
	at com.google.firebase.perf.v1.TraceMetric.<clinit>(TraceMetric.java:1945)
	at com.google.firebase.perf.v1.TraceMetric.newBuilder(TraceMetric.java:941)
	at com.google.firebase.perf.metrics.AppStartTrace.<init>(AppStartTrace.java:194)
	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:171)
	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:158)
	at com.google.firebase.perf.FirebasePerfEarly.<init>(FirebasePerfEarly.java:49)
	at com.google.firebase.perf.FirebasePerfRegistrar.lambda$getComponents$0(FirebasePerfRegistrar.java:75)
	at com.google.firebase.perf.FirebasePerfRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(Lazy.java:53)
	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:606)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:299)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:263)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:248)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

INSTRUMENTATION_STATUS_CODE: -2

18:35:23.384 detox[91222] i child-process:SPAWN_STDOUT INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

18:35:23.385 detox[91222] i child-process:SPAWN_END /home/jeferson_brito/Android/Sdk/platform-tools/adb -s emulator-17034 shell am instrument -w -r -e detoxServer ws://localhost:42627 -e detoxSessionId 56e33148-6998-daa5-6a0e-e22f56dcc764 -e debug false com.apptest.test/androidx.test.runner.AndroidJUnitRunner exited with code #0
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
18:38:00.594 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 shell "rm -fr /data/local/tmp/detox"
18:38:00.615 detox[91607] [90mi[39m 
18:38:00.615 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 shell "mkdir -p /data/local/tmp/detox"
18:38:00.635 detox[91607] [90mi[39m 
18:38:00.635 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 push "/home/jeferson_brito/projects/Frontend-Code/android/app/build/outputs/apk/debug/app-debug.apk" "/data/local/tmp/detox/Application.apk"
18:38:00.902 detox[91607] [90mi[39m /home/jeferson_brito/projects/Frontend-Code/android/app/build/outputs/apk/debug/app-debug.apk: 1 file pushed, 0 skipped. 348.6 MB/s (89528172 bytes in 0.245s)

18:38:00.906 detox[91607] [90mi[39m /home/jeferson_brito/Android/Sdk/platform-tools/adb -s emulator-17034 shell pm install -r -g -t /data/local/tmp/detox/Application.apk
18:38:01.278 detox[91607] [90mi[39m Success

18:38:01.279 detox[91607] [90mi[39m /home/jeferson_brito/Android/Sdk/platform-tools/adb -s emulator-17034 shell pm install -r -g -t /data/local/tmp/detox/Application.apk exited with code #0
18:38:01.279 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 push "/home/jeferson_brito/projects/Frontend-Code/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk" "/data/local/tmp/detox/Test.apk"
18:38:01.303 detox[91607] [90mi[39m /home/jeferson_brito/projects/Frontend-Code/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk: 1 file pushed, 0 skipped. 686.6 MB/s (2854075 bytes in 0.004s)

18:38:01.309 detox[91607] [90mi[39m /home/jeferson_brito/Android/Sdk/platform-tools/adb -s emulator-17034 shell pm install -r -g -t /data/local/tmp/detox/Test.apk
18:38:01.398 detox[91607] [90mi[39m Success

18:38:01.399 detox[91607] [90mi[39m /home/jeferson_brito/Android/Sdk/platform-tools/adb -s emulator-17034 shell pm install -r -g -t /data/local/tmp/detox/Test.apk exited with code #0
18:38:01.399 detox[91607] [90mB[39m reverseTcpPort
  args: (8081)
18:38:01.399 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 reverse tcp:8081 tcp:8081
18:38:01.408 detox[91607] [90mi[39m 
18:38:01.409 detox[91607] [90mE[39m reverseTcpPort
18:38:01.409 detox[91607] [90mE[39m installApp
18:38:01.409 detox[91607] [90mB[39m selectApp
  args: ("default")
18:38:01.409 detox[91607] [90mB[39m terminateApp
  args: ()
18:38:01.409 detox[91607] [90mB[39m onBeforeTerminateApp
  args: ({"deviceId":"emulator-17034","bundleId":"com.apptest"})
18:38:01.409 detox[91607] [90mE[39m onBeforeTerminateApp
18:38:01.409 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 shell "am force-stop com.apptest"
18:38:01.442 detox[91607] [90mi[39m 
18:38:01.442 detox[91607] [90mB[39m onTerminateApp
  args: ({"deviceId":"emulator-17034","bundleId":"com.apptest"})
18:38:01.442 detox[91607] [90mE[39m onTerminateApp
18:38:01.442 detox[91607] [90mE[39m terminateApp
18:38:01.442 detox[91607] [90mE[39m selectApp
18:38:01.443 detox[91607] [90mE[39m set up environment
18:38:03.800 detox[91607] [90mi[39m chat.test.ts is assigned to emulator-17034 (Pixel_XL_API_33)
18:38:03.801 detox[91607] [90mB[39m run the tests
18:38:03.801 detox[91607] [90mB[39m onRunDescribeStart
  args: ({"name":"ROOT_DESCRIBE_BLOCK"})
18:38:03.802 detox[91607] [90mE[39m onRunDescribeStart
18:38:03.802 detox[91607] [90mB[39m Test
18:38:03.802 detox[91607] [90mB[39m onRunDescribeStart
  args: ({"name":"Test"})
18:38:03.802 detox[91607] [90mE[39m onRunDescribeStart
18:38:03.803 detox[91607] [90mB[39m beforeAll
18:38:03.806 detox[91607] [90mB[39m launchApp
  args: ()
18:38:03.806 detox[91607] [90mB[39m terminateApp
  args: ("com.apptest")
18:38:03.806 detox[91607] [90mB[39m onBeforeTerminateApp
  args: ({"deviceId":"emulator-17034","bundleId":"com.apptest"})
18:38:03.806 detox[91607] [90mE[39m onBeforeTerminateApp
18:38:03.806 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 shell "am force-stop com.apptest"
18:38:03.835 detox[91607] [90mi[39m 
18:38:03.835 detox[91607] [90mB[39m onTerminateApp
  args: ({"deviceId":"emulator-17034","bundleId":"com.apptest"})
18:38:03.835 detox[91607] [90mE[39m onTerminateApp
18:38:03.835 detox[91607] [90mE[39m terminateApp
18:38:03.836 detox[91607] [90mB[39m onBeforeLaunchApp
  args: ({"deviceId":"emulator-17034","bundleId":"com.apptest","launchArgs":{"detoxServer":"ws://localhost:45663","detoxSessionId":"c84eb93b-ff54-bb1b-f521-c6f269f4df2f"}})
18:38:03.836 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 shell "date +\"%m-%d %T.000\""
18:38:03.866 detox[91607] [90mi[39m 06-15 18:38:03.000

18:38:03.866 detox[91607] [90mE[39m onBeforeLaunchApp
18:38:03.867 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 reverse tcp:45663 tcp:45663
18:38:03.883 detox[91607] [90mi[39m 45663

18:38:03.883 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 shell "pm list instrumentation"
18:38:03.910 detox[91607] [90mi[39m instrumentation:com.apptest.test/androidx.test.runner.AndroidJUnitRunner (target=com.apptest)

18:38:03.923 detox[91607] [90mi[39m /home/jeferson_brito/Android/Sdk/platform-tools/adb -s emulator-17034 shell am instrument -w -r -e detoxServer ws://localhost:45663 -e detoxSessionId c84eb93b-ff54-bb1b-f521-c6f269f4df2f -e debug false com.apptest.test/androidx.test.runner.AndroidJUnitRunner
18:38:04.424 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 shell "ps | grep \"com\.apptest$\""
18:38:04.466 detox[91607] [90mi[39m u0_a175       5716   386 14730688 125784 0                  0 R com.apptest

18:38:04.467 detox[91607] [90mB[39m onLaunchApp
  args: ({"deviceId":"emulator-17034","bundleId":"com.apptest","launchArgs":{"detoxServer":"ws://localhost:45663","detoxSessionId":"c84eb93b-ff54-bb1b-f521-c6f269f4df2f"},"pid":5716})
18:38:04.467 detox[91607] [90mi[39m starting ADBLogcatRecording
18:38:04.481 detox[91607] [90mi[39m /home/jeferson_brito/Android/Sdk/platform-tools/adb -s emulator-17034 shell "logcat -T \"06-15 18:38:03.000\" --pid=5716 -f /sdcard/18380161_0.log"
18:38:04.481 detox[91607] [90mE[39m onLaunchApp
18:38:04.725 detox[91607] [90mi[39m INSTRUMENTATION_STATUS: stack=java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/~~efXr8cHsViCBFGY53wrieQ==/com.apptest.test-yUdMbTmOfWBCZPFNqubrKQ==/base.apk)
	at com.google.firebase.perf.v1.TraceMetric.<clinit>(TraceMetric.java:1945)
	at com.google.firebase.perf.v1.TraceMetric.newBuilder(TraceMetric.java:941)
	at com.google.firebase.perf.metrics.AppStartTrace.<init>(AppStartTrace.java:194)
	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:171)
	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:158)
	at com.google.firebase.perf.FirebasePerfEarly.<init>(FirebasePerfEarly.java:49)
	at com.google.firebase.perf.FirebasePerfRegistrar.lambda$getComponents$0(FirebasePerfRegistrar.java:75)
	at com.google.firebase.perf.FirebasePerfRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(Lazy.java:53)
	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:606)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:299)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:263)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:248)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

INSTRUMENTATION_STATUS: stream=
Process crashed before executing the test(s):
java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/~~efXr8cHsViCBFGY53wrieQ==/com.apptest.test-yUdMbTmOfWBCZPFNqubrKQ==/base.apk)
	at com.google.firebase.perf.v1.TraceMetric.<clinit>(TraceMetric.java:1945)
	at com.google.firebase.perf.v1.TraceMetric.newBuilder(TraceMetric.java:941)
	at com.google.firebase.perf.metrics.AppStartTrace.<init>(AppStartTrace.java:194)
	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:171)
	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:158)
	at com.google.firebase.perf.FirebasePerfEarly.<init>(FirebasePerfEarly.java:49)
	at com.google.firebase.perf.FirebasePerfRegistrar.lambda$getComponents$0(FirebasePerfRegistrar.java:75)
	at com.google.firebase.perf.FirebasePerfRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(Lazy.java:53)
	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:606)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:299)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:263)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:248)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

INSTRUMENTATION_STATUS_CODE: -2

18:38:04.752 detox[91607] [90mi[39m INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

18:38:04.753 detox[91607] [90mi[39m /home/jeferson_brito/Android/Sdk/platform-tools/adb -s emulator-17034 shell am instrument -w -r -e detoxServer ws://localhost:45663 -e detoxSessionId c84eb93b-ff54-bb1b-f521-c6f269f4df2f -e debug false com.apptest.test/androidx.test.runner.AndroidJUnitRunner exited with code #0
18:38:04.753 detox[91607] [90mi[39m An error occurred while waiting for the app to become ready. Waiting for disconnection...
  error: Failed to run application on the device
  
  HINT: Most likely, your main activity has crashed prematurely.
  
  Native stacktrace dump:
  java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/~~efXr8cHsViCBFGY53wrieQ==/com.apptest.test-yUdMbTmOfWBCZPFNqubrKQ==/base.apk)
  	at com.google.firebase.perf.v1.TraceMetric.<clinit>(TraceMetric.java:1945)
  	at com.google.firebase.perf.v1.TraceMetric.newBuilder(TraceMetric.java:941)
  	at com.google.firebase.perf.metrics.AppStartTrace.<init>(AppStartTrace.java:194)
  	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:171)
  	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:158)
  	at com.google.firebase.perf.FirebasePerfEarly.<init>(FirebasePerfEarly.java:49)
  	at com.google.firebase.perf.FirebasePerfRegistrar.lambda$getComponents$0(FirebasePerfRegistrar.java:75)
  	at com.google.firebase.perf.FirebasePerfRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
  	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
  	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
  	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
  	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
  	at com.google.firebase.components.Lazy.get(Lazy.java:53)
  	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
  	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
  	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:606)
  	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:299)
  	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:263)
  	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:248)
  	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
  	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
  	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
  	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
  	at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
  	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
  	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
  	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
  	at android.os.Handler.dispatchMessage(Handler.java:106)
  	at android.os.Looper.loopOnce(Looper.java:201)
  	at android.os.Looper.loop(Looper.java:288)
  	at android.app.ActivityThread.main(ActivityThread.java:7872)
  	at java.lang.reflect.Method.invoke(Native Method)
  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  
18:38:04.754 detox[91607] [90mi[39m The app disconnected.
18:38:04.754 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 reverse --remove tcp:45663
18:38:04.767 detox[91607] [90mE[39m launchApp
  error: Failed to run application on the device
  
  HINT: Most likely, your main activity has crashed prematurely.
  
  Native stacktrace dump:
  java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/~~efXr8cHsViCBFGY53wrieQ==/com.apptest.test-yUdMbTmOfWBCZPFNqubrKQ==/base.apk)
  	at com.google.firebase.perf.v1.TraceMetric.<clinit>(TraceMetric.java:1945)
  	at com.google.firebase.perf.v1.TraceMetric.newBuilder(TraceMetric.java:941)
  	at com.google.firebase.perf.metrics.AppStartTrace.<init>(AppStartTrace.java:194)
  	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:171)
  	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:158)
  	at com.google.firebase.perf.FirebasePerfEarly.<init>(FirebasePerfEarly.java:49)
  	at com.google.firebase.perf.FirebasePerfRegistrar.lambda$getComponents$0(FirebasePerfRegistrar.java:75)
  	at com.google.firebase.perf.FirebasePerfRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
  	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
  	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
  	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
  	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
  	at com.google.firebase.components.Lazy.get(Lazy.java:53)
  	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
  	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
  	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:606)
  	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:299)
  	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:263)
  	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:248)
  	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
  	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
  	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
  	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
  	at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
  	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
  	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
  	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
  	at android.os.Handler.dispatchMessage(Handler.java:106)
  	at android.os.Looper.loopOnce(Looper.java:201)
  	at android.os.Looper.loop(Looper.java:288)
  	at android.app.ActivityThread.main(ActivityThread.java:7872)
  	at java.lang.reflect.Method.invoke(Native Method)
  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  
18:38:04.767 detox[91607] [90mB[39m onHookFailure
  args: ({"error":{"name":"DetoxRuntimeError"},"hook":"beforeAll"})
18:38:04.767 detox[91607] [90mE[39m onHookFailure
18:38:04.767 detox[91607] [90mE[39m beforeAll
  error: Failed to run application on the device
  
  HINT: Most likely, your main activity has crashed prematurely.
  
  Native stacktrace dump:
  java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/~~efXr8cHsViCBFGY53wrieQ==/com.apptest.test-yUdMbTmOfWBCZPFNqubrKQ==/base.apk)
  	at com.google.firebase.perf.v1.TraceMetric.<clinit>(TraceMetric.java:1945)
  	at com.google.firebase.perf.v1.TraceMetric.newBuilder(TraceMetric.java:941)
  	at com.google.firebase.perf.metrics.AppStartTrace.<init>(AppStartTrace.java:194)
  	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:171)
  	at com.google.firebase.perf.metrics.AppStartTrace.getInstance(AppStartTrace.java:158)
  	at com.google.firebase.perf.FirebasePerfEarly.<init>(FirebasePerfEarly.java:49)
  	at com.google.firebase.perf.FirebasePerfRegistrar.lambda$getComponents$0(FirebasePerfRegistrar.java:75)
  	at com.google.firebase.perf.FirebasePerfRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
  	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
  	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
  	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
  	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
  	at com.google.firebase.components.Lazy.get(Lazy.java:53)
  	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
  	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
  	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:606)
  	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:299)
  	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:263)
  	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:248)
  	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
  	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
  	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
  	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
  	at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
  	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
  	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
  	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
  	at android.os.Handler.dispatchMessage(Handler.java:106)
  	at android.os.Looper.loopOnce(Looper.java:201)
  	at android.os.Looper.loop(Looper.java:288)
  	at android.app.ActivityThread.main(ActivityThread.java:7872)
  	at java.lang.reflect.Method.invoke(Native Method)
  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  
18:38:04.768 detox[91607] [90mB[39m first test
18:38:04.768 detox[91607] [90mB[39m onRunDescribeStart
  args: ({"name":"first test"})
18:38:04.768 detox[91607] [90mE[39m onRunDescribeStart
18:38:04.769 detox[91607] [90mB[39m just login
18:38:04.769 detox[91607] [90mi[39m Test > first test: just login
18:38:04.770 detox[91607] [90mE[39m just login
18:38:04.770 detox[91607] [90mi[39m Test > first test: just login [FAIL]
18:38:04.771 detox[91607] [90mB[39m onRunDescribeFinish
  args: ({"name":"first test"})
18:38:04.771 detox[91607] [90mE[39m onRunDescribeFinish
18:38:04.771 detox[91607] [90mE[39m first test
18:38:04.772 detox[91607] [90mB[39m onRunDescribeFinish
  args: ({"name":"Test"})
18:38:04.772 detox[91607] [90mE[39m onRunDescribeFinish
18:38:04.772 detox[91607] [90mE[39m Test
18:38:04.772 detox[91607] [90mB[39m onRunDescribeFinish
  args: ({"name":"ROOT_DESCRIBE_BLOCK"})
18:38:04.772 detox[91607] [90mE[39m onRunDescribeFinish
18:38:04.772 detox[91607] [90mE[39m run the tests
18:38:04.786 detox[91607] [90mB[39m tear down environment
18:38:04.787 detox[91607] [90mB[39m onBeforeCleanup
  args: ()
18:38:04.789 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 shell du /sdcard/18380161_0.log
18:38:04.802 detox[91607] [90mi[39m 
18:38:04.802 detox[91607] [90mi[39m saving ADBLogcatRecording to: artifacts/android.emu.debug.2023-06-15 21-37-59Z/emulator-17034 2023-06-15 21-38-04Z.startup.log
18:38:04.802 detox[91607] [90mi[39m stopping ADBLogcatRecording
18:38:04.814 detox[91607] [90mi[39m 4	/sdcard/18380161_0.log

18:38:04.814 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 shell "date +\"%m-%d %T.000\""
18:38:04.839 detox[91607] [90mi[39m 06-15 18:38:04.000

18:38:04.841 detox[91607] [90mi[39m sending SIGINT to: /home/jeferson_brito/Android/Sdk/platform-tools/adb -s emulator-17034 shell logcat -T "06-15 18:38:03.000" --pid=5716 -f /sdcard/18380161_0.log
18:38:04.841 detox[91607] [90mi[39m /home/jeferson_brito/Android/Sdk/platform-tools/adb -s emulator-17034 shell "logcat -T \"06-15 18:38:03.000\" --pid=5716 -f /sdcard/18380161_0.log" terminated with SIGINT
18:38:04.842 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 pull "/sdcard/18380161_0.log" "artifacts/android.emu.debug.2023-06-15 21-37-59Z/emulator-17034 2023-06-15 21-38-04Z.startup.log"
18:38:04.859 detox[91607] [90mi[39m /sdcard/18380161_0.log: 1 file pulled, 0 skipped. 65.0 MB/s (53248 bytes in 0.001s)

18:38:04.859 detox[91607] [90mi[39m "/home/jeferson_brito/Android/Sdk/platform-tools/adb" -s emulator-17034 shell "rm  \"/sdcard/18380161_0.log\""
18:38:04.891 detox[91607] [90mi[39m 
18:38:04.892 detox[91607] [90mi[39m saving FileArtifact to: artifacts/android.emu.debug.2023-06-15 21-37-59Z/detox_pid_91607.json.log { append: true }
18:38:04.892 detox[91607] [90mi[39m saving FileArtifact to: artifacts/android.emu.debug.2023-06-15 21-37-59Z/detox_pid_91607.log { append: true }
18:38:04.892 detox[91607] [90mE[39m onBeforeCleanup
18:38:04.892 detox[91607] [90mi[39m Detox can't seem to connect to the test app(s)!
```

</details>

**Comment by RohovDmytro** [comment]
Yeah. Same issue. I've fixed it by patching. I've patched the expo's Detox config plugin to make things work:

````
diff --git a/node_modules/@config-plugins/detox/build/withDetoxTestAppGradle.js b/node_modules/@config-plugins/detox/build/withDetoxTestAppGradle.js
index 5df4038..bf90074 100644
--- a/node_modules/@config-plugins/detox/build/withDetoxTestAppGradle.js
+++ b/node_modules/@config-plugins/detox/build/withDetoxTestAppGradle.js
@@ -23,7 +23,7 @@ const withDetoxTestAppGradle = (config) => {
 };
 function setGradleAndroidTestImplementation(buildGradle) {
     buildGradle = pushGradleDependency(buildGradle, "implementation 'androidx.appcompat:appcompat:1.1.0'");
-    buildGradle = pushGradleDependency(buildGradle, "androidTestImplementation('com.wix:detox:+')");
+    buildGradle = pushGradleDependency(buildGradle, "androidTestImplementation('com.wix:detox:+') { exclude module: 'protobuf-lite' }");
     return buildGradle;
 }
 exports.setGradleAndroidTestImplementation = setGradleAndroidTestImplementation;

````

**Comment by asafkorem** [comment]
This is a known issue with Espresso and Firebase, see: https://github.com/android/android-test/issues/999.
Thanks for sharing the patch @RohovDmytro. @jeferson-sb, did this patch work for you?

@d4vidi do you think we can exclude `protobuf-lite` within Detox?

**Comment by jeferson-sb** [comment]
Hi @RohovDmytro and @asafkorem thanks for the reply. Yes, that patch works. I was able to fix by excluding the protobuf-lite module from com.wix.detox

**Comment by asafkorem** [comment]
@jeferson-sb thanks for the update! Glad it worked 😃

**Comment by olehdutko** [comment]
Hi,
It looks like this issue is still actual for detox 20.20.3

Do you know if I can patch it locally?
